# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7FxDoUwi_sTUJqof18Ai0hihXonJOE2
"""

!pip install torch torchvision torchaudio --upgrade
!pip install transformers datasets evaluate accelerate huggingface_hub

from huggingface_hub import notebook_login
notebook_login()

from datasets import load_dataset

dataset = load_dataset("AyushiSri101/promptium-dataset")
dataset

from transformers import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

def tokenize_function(example):
    return tokenizer(example["text"], truncation=True, padding="max_length", max_length=128)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets = tokenized_datasets.remove_columns(["text"])
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
tokenized_datasets.set_format("torch")

print(dataset)
print(dataset["train"].column_names)

train_dataset = tokenized_datasets["train"]
test_dataset = tokenized_datasets["test"]

from transformers import RobertaForSequenceClassification

model = RobertaForSequenceClassification.from_pretrained("roberta-base", num_labels=2)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer
)

trainer.train()

eval_metrics = trainer.evaluate(eval_dataset=test_dataset)
print(eval_metrics)
